[package]
name = "dialogue_test"
version = "0.1.0"
edition = "2021"

[dependencies]
ears = { git = "https://github.com/d4140n-4h3-1/ears.git" }
inline_colorization = { git = "https://github.com/d4140n-4h3-1/inline_colorization.git" }
rand = "0.8.5"
